---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# ivx

The goal of ivx is to ...

## Installation


You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("kvasilopoulos/ivx")
```
## Example

Load ivx and dplyr for data managment
```{r message = FALSE}
library(ivx)
library(dplyr)
```

This is a basic example, lets load the data first:
```{r example}
# Monthly data from Kostakis et al (2014)
datam %>%
  names()

univariate <- datam %>%
  select(Ret, D_P)

multivariate <- datam %>%
  select(Ret, D_P, TBL)

```

And then do the univariate estimation:
```{r uni}
ivx(Ret ~ D_P, data = univariate) %>% 
  summary()

qtest(univariate$Ret, univariate$D_P)
```

And the multivariate estimation, for one or multiple horizons:
```{r multi}
ivx(Ret ~ D_P + TBL, data = multivariate) %>% 
  summary()

ivx(Ret ~ D_P + TBL, data = multivariate, horizon = 4) %>% 
  summary()

```
