// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ivx_fit_cpp
List ivx_fit_cpp(const arma::vec& y, const arma::mat& X, int K, double beta, double cz, int bandwidth, bool robust);
RcppExport SEXP _ivx_ivx_fit_cpp(SEXP ySEXP, SEXP XSEXP, SEXP KSEXP, SEXP betaSEXP, SEXP czSEXP, SEXP bandwidthSEXP, SEXP robustSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type cz(czSEXP);
    Rcpp::traits::input_parameter< int >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< bool >::type robust(robustSEXP);
    rcpp_result_gen = Rcpp::wrap(ivx_fit_cpp(y, X, K, beta, cz, bandwidth, robust));
    return rcpp_result_gen;
END_RCPP
}
// sub_ivx_cpp
arma::mat sub_ivx_cpp(const arma::vec& y, const arma::mat& x, const arma::mat& z, const arma::uvec& start, const arma::uvec& end, bool robust);
RcppExport SEXP _ivx_sub_ivx_cpp(SEXP ySEXP, SEXP xSEXP, SEXP zSEXP, SEXP startSEXP, SEXP endSEXP, SEXP robustSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type end(endSEXP);
    Rcpp::traits::input_parameter< bool >::type robust(robustSEXP);
    rcpp_result_gen = Rcpp::wrap(sub_ivx_cpp(y, x, z, start, end, robust));
    return rcpp_result_gen;
END_RCPP
}
// var_sim_cpp
arma::mat var_sim_cpp(const arma::mat& v, const List& A);
RcppExport SEXP _ivx_var_sim_cpp(SEXP vSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const List& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(var_sim_cpp(v, A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ivx_ivx_fit_cpp", (DL_FUNC) &_ivx_ivx_fit_cpp, 7},
    {"_ivx_sub_ivx_cpp", (DL_FUNC) &_ivx_sub_ivx_cpp, 6},
    {"_ivx_var_sim_cpp", (DL_FUNC) &_ivx_var_sim_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ivx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
