# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ivx_fit_cpp <- function(y, X, K = 1L) {
    .Call(`_ivx_ivx_fit_cpp`, y, X, K)
}

